# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it.
      # As required by OpenSSF Scorecard,
      # we pin this to a specific hash value to prevent use of an unknown
      # (and possibly subverted) version.
      # Update by consulting: https://github.com/actions/checkout/releases
      # We include the hash after '@', and comment "pin @SIMPLE-NAME"; this is
      # the naming convention of https://github.com/mheap/pin-github-action
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin @v2.3.4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Run Brakeman. See https://github.com/devmasx/brakeman-linter-action
      - name: Brakeman linter
        # To review release options see:
        # https://github.com/devmasx/brakeman-linter-action/releases
        uses: devmasx/brakeman-linter-action@0dc80fcccf87915ccb1761669014015214f36287 # pin@v1.0.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
